Dev_Center/Models/ApplicationSystems.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Dev_Center.Models
{
    public class ApplicationSystems
    {
        public string ApplicationSystemOwner;
        public string ApplicationType { get; set; }
        public string Authority { get; set; }
        public string Changedby { get; set; }
        public double Checkout_version { get; set; }
        public string Constraints { get; set; }
        public string Createdby { get; set; }
        public string DatawarehouseFlag { get; set; }
        public DateTime DateChanged { get; set; }
        public DateTime DateCreated { get; set; }
        public string DisplayTitle { get; set; }
        public string ElementTypeName { get; set; }
        public int ID { get; set; }
        public string LatestVersionFlag { get; set; }
        public string name { get; set; }
        public double NumberofTimesModifed { get; set; }
        public double ParentReference { get; set; }
        public string Priority { get; set; }
        public string Status { get; set; }
        public double Types { get; set; }
        public string UDP0 { get; set; }
        public string UDP1 { get; set; }
        public string UDP2 { get; set; }
        public string UDP3 { get; set; }
        public string UDP4 { get; set; }
        public string UDP5 { get; set; }
        public string UDP6 { get; set; }
        public string UDP7 { get; set; }
        public string UDP8 { get; set; }
        public string UDP9 { get; set; }
        public string UDP10 { get; set; }
        public string UDP11 { get; set; }
        public string UDP12 { get; set; }
        public string UDP13 { get; set; }
        public string UDP14 { get; set; }
        public string UDP15 { get; set; }
        public string UDP16 { get; set; }
        public string UDP17 { get; set; }
        public string UDP18 { get; set; }
        public string UDP19 { get; set; }
        public string UDP20 { get; set; }
        public double Version { get; set; }
        public DateTime VersionDate { get; set; }
    }
}

Dev_Center/Models/ErrorViewModel.cs
using System;

namespace Dev_Center.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Dev_Center/Models/SearchModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Dev_Center.Models
{
    public class SearchModel
    {
        public string FilterInput { get; set; }
    }
}

Dev_Center/Controllers/DomainController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Dev_Center.Repository;
using System.Data;
using Microsoft.AspNetCore.Mvc;
using Dev_Center.Models;
using System.Diagnostics;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Dev_Center.Controllers
{
    /*
     * Controller welche die Anfragen für die Domain Seite behandelt
     */
    public class DomainController : Controller
    {
        TableRepository trep = new TableRepository();
        public List<string[]> ldt;

        public IActionResult Index()
        {
            ldt = new List<string[]>();
            ldt = trep.GetTable("select name,version from CI_APPLICATION_SYSTEMS order by version desc");
            ViewData["List"] = ldt;
            return View();
        }
        [Route("/DomainList")]
        public IActionResult DomainList()
        {
            ldt = new List<string[]>();
             ldt = trep.GetTable("select Table_name from User_tables");
            ViewData["DomainList"]=ldt;
            return View();
        }
        [Route("/DomainDetail/{Domain=}")]
        public IActionResult DomainDetail(string domain)
        {
            ldt = new List<string[]>();
            ldt = trep.GetTable($"select * from {domain.ToString()}");
            ViewData["DomainDetail"] = ldt;
            return View();
        }
        [HttpPost]
        public ActionResult Filter(string filterv)
        {
            ldt = new List<string[]>();
            if(filterv == null)
                ldt = trep.GetTable("select name,version from CI_APPLICATION_SYSTEMS order by version desc");
            else
                ldt = trep.GetTable($"select Table_name from User_tables where Table_name like '{filterv}'");
            ViewData["DomainList"] = ldt;
            return View();
        }
    }
}

Dev_Center/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Dev_Center.Models;

namespace Dev_Center.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Dev_Center/Controllers/TableController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Dev_Center.Repository;
using System.Data;
using Microsoft.AspNetCore.Mvc;
using Dev_Center.Models;
using System.Diagnostics;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Dev_Center.Controllers
{
    /*
     * Controller welche die Anfragen für die Table Seite behandelt
     */
    public class TableController : Controller
    {
        TableRepository trep = new TableRepository();
        public List<string[]> ldt;

        public IActionResult Index()
        {
            ldt = new List<string[]>();
            ldt = trep.GetTable("select name,version from CI_APPLICATION_SYSTEMS order by version desc");
            ViewData["List"] = ldt;
            return View();
        }
        [Route("/TableList")]
        public IActionResult TableList()
        {
            ldt = new List<string[]>();
             ldt = trep.GetTable("select Table_name from User_tables");
            ViewData["TableList"]=ldt;
            return View();
        }
        [Route("/TableDetail/{Table=}")]
        public IActionResult TableDetail(string Table)
        {
            ldt = new List<string[]>();
            ldt = trep.GetTable($"select * from {Table.ToString()}");
            ViewData["TableDetail"] = ldt;
            return View();
        }
        [HttpPost]
        public ActionResult Filter(string filterv)
        {
            ldt = new List<string[]>();
            if(filterv == null)
                ldt = trep.GetTable("select Table_name from User_tables");
            else
                ldt = trep.GetTable($"select Table_name from User_tables where Table_name like '{filterv}'");
            ViewData["TableList"] = ldt;
            return View();
        }
    }
}

Dev_Center/Views/Domain/DomainDetail.cshtml
<style>
    table, th, td {
        border: 1px solid black;
        border-collapse: collapse;
        padding: 15px;
    }

    .side {
        flex: 30%;
        background-color: #f1f1f1;
        padding: 20px;
    }

    /* Main column */
    .main {
        flex: 70%;
        background-color: white;
        padding: 20px;
    }
</style>
<h2>DomainDetail</h2>
<div class="row">

    <div class="col-md-2">
        <table>
            <tr>
                @{
                    List<string[]> list = (List<string[]>)ViewData["DomainDetail"];
                    for (int j = 0; j < list[0].Length - 1; j++)
                    {
                        <th>@list[0][j].ToString()</th>
                    }
                }
            </tr>
            @{
                for (int i = 1; i < list.Count; i++)
                {
                    <tr>
                        @for (int j = 0; j < list[i].Length - 1; j++)
                        {
                            <td>@list[i][j].ToString()</td>
                        }
                    </tr>
                }
            }
        </table>
    </div>
</div>

Dev_Center/Views/Domain/DomainList.cshtml
<style>
    table, th, td {
        border: 1px solid black;
        border-collapse: collapse;
        padding: 15px;
    }

    .side {
        flex: 30%;
        background-color: #f1f1f1;
        padding: 20px;
    }

    /* Main column */
    .main {
        flex: 70%;
        background-color: white;
        padding: 20px;
    }
</style>
<h2>DomainList</h2>
<div>

    @using (Html.BeginForm("Filter", "Domain"))
    {
        <input name="Filterv" id="Filterv" type="text" />

        <input type="submit" value="Filter" />
    }
</div>
<div class="row">
    <div class="col-md-2">
        <table>
            <tr>
                @{
                    List<string[]> list = (List<string[]>)ViewData["DomainList"];
                    for (int j = 0; j < list[0].Length - 1; j++)
                    {
                        <th>@list[0][j].ToString()</th>
                    }
                }
            </tr>
            @{
                for (int i = 1; i < list.Count; i++)
                {
                    <tr>
                        @for (int j = 0; j < list[i].Length - 1; j++)
                        {
                            if (j == 0)
                            {
                                <td>@Html.ActionLink(list[i][j].ToString(), $"DomainDetail", "Domain", new { domain = list[i][j].ToString() }, null)</td>
                            }
                            else
                            {
                                <td>@list[i][j].ToString()</td>
                            }
                        }
                    </tr>
                }
            }
        </table>
    </div>
</div>

Dev_Center/Views/Domain/Filter.cshtml
<style>
    table, th, td {
        border: 1px solid black;
        border-collapse: collapse;
        padding: 15px;
    }

    .side {
        flex: 30%;
        background-color: #f1f1f1;
        padding: 20px;
    }

    /* Main column */
    .main {
        flex: 70%;
        background-color: white;
        padding: 20px;
    }
</style>
<h2>DomainList</h2>
<div>

    @using (Html.BeginForm("Filter", "Domain"))
    {
        <input name="Filterv" id="Filterv" type="text" />

        <input type="submit" value="Filter" />
    }
</div>
<div class="row">
    <div class="col-md-2">
        <table>
            <tr>
                @{
                    List<string[]> list = (List<string[]>)ViewData["DomainList"];
                    for (int j = 0; j < list[0].Length - 1; j++)
                    {
                        <th>@list[0][j].ToString()</th>
                    }
                }
            </tr>
            @{
                for (int i = 1; i < list.Count; i++)
                {
                    <tr>
                        @for (int j = 0; j < list[i].Length - 1; j++)
                        {
                            if (j == 0)
                            {
                                <td>@Html.ActionLink(list[i][j].ToString(), $"DomainDetail", "Domain", new { table = list[i][j].ToString() }, null)</td>
                            }
                            else
                            {
                                <td>@list[i][j].ToString()</td>
                            }
                        }
                    </tr>
                }
            }
        </table>
    </div>
</div>

Dev_Center/Views/Domain/Index.cshtml
<style>
    table, th, td {
        border: 1px solid black;
        border-collapse: collapse;
        padding: 15px;
    }

    .side {
        flex: 30%;
        background-color: #f1f1f1;
        padding: 20px;
    }

    /* Main column */
    .main {
        flex: 70%;
        background-color: white;
        padding: 20px;
    }
</style>
<h2>Domain</h2>
<div class="row">
    <div class="col-md-2">
        <table>
            <tr>
                @{
                    List<string[]> list = (List<string[]>)ViewData["List"];
                    for (int j = 0; j < list[0].Length-1; j++)
                    {
                        <th>@list[0][j].ToString()</th>
                    }
                }
            </tr>
            @{
                for (int i = 1; i < list.Count; i++)
                {
                    <tr>
                        @for (int j = 0; j < list[i].Length-1; j++)
                        {
                            if (j == 0)
                            {
                            <td>@Html.ActionLink(list[i][j].ToString(), "DomainList", "Domain")</td>
                            }
                            else
                            {
                                <td>@list[i][j].ToString()</td>
                            }
                        }
                    </tr>
                }
            }
        </table>
    </div>
</div>

Dev_Center/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

Dev_Center/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Dev_Center/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

Dev_Center/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title - Dev Center</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Dev Center</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Table" asp-action="Index">Table</a></li>
                    <li><a asp-area="" asp-controller="Domain" asp-action="Index">Domain</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - Dev_Center</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

Dev_Center/Views/Table/Filter.cshtml
<style>
    table, th, td {
        border: 1px solid black;
        border-collapse: collapse;
        padding: 15px;
    }

    .side {
        flex: 30%;
        background-color: #f1f1f1;
        padding: 20px;
    }

    /* Main column */
    .main {
        flex: 70%;
        background-color: white;
        padding: 20px;
    }
</style>
<h2>TableList</h2>
<div>

    @using (Html.BeginForm("Filter", "Table"))
    {
        <input name="Filterv" id="Filterv" type="text" />

        <input type="submit" value="Filter" />
    }
</div>
<div class="row">
    <div class="col-md-2">
        <table>
            <tr>
                @{
                    List<string[]> list = (List<string[]>)ViewData["TableList"];
                    for (int j = 0; j < list[0].Length - 1; j++)
                    {
                        <th>@list[0][j].ToString()</th>
                    }
                }
            </tr>
            @{
                for (int i = 1; i < list.Count; i++)
                {
                    <tr>
                        @for (int j = 0; j < list[i].Length - 1; j++)
                        {
                            if (j == 0)
                            {
                                <td>@Html.ActionLink(list[i][j].ToString(), $"TableDetail", "Display", new { table = list[i][j].ToString() }, null)</td>
                            }
                            else
                            {
                                <td>@list[i][j].ToString()</td>
                            }
                        }
                    </tr>
                }
            }
        </table>
    </div>
</div>

Dev_Center/Views/Table/Index.cshtml
<style>
    table, th, td {
        border: 1px solid black;
        border-collapse: collapse;
        padding: 15px;
    }

    .side {
        flex: 30%;
        background-color: #f1f1f1;
        padding: 20px;
    }

    /* Main column */
    .main {
        flex: 70%;
        background-color: white;
        padding: 20px;
    }
</style>
<h2>Table</h2>
<div class="row">
    <div class="col-md-2">
        <table>
            <tr>
                @{
                    List<string[]> list = (List<string[]>)ViewData["List"];
                    for (int j = 0; j < list[0].Length-1; j++)
                    {
                        <th>@list[0][j].ToString()</th>
                    }
                }
            </tr>
            @{
                for (int i = 1; i < list.Count; i++)
                {
                    <tr>
                        @for (int j = 0; j < list[i].Length-1; j++)
                        {
                            if (j == 0)
                            {
                            <td>@Html.ActionLink(list[i][j].ToString(), "TableList", "Table")</td>
                            }
                            else
                            {
                                <td>@list[i][j].ToString()</td>
                            }
                        }
                    </tr>
                }
            }
        </table>
    </div>
</div>

Dev_Center/Views/Table/TableDetail.cshtml
<style>
    table, th, td {
        border: 1px solid black;
        border-collapse: collapse;
        padding: 15px;
    }

    .side {
        flex: 30%;
        background-color: #f1f1f1;
        padding: 20px;
    }

    /* Main column */
    .main {
        flex: 70%;
        background-color: white;
        padding: 20px;
    }
</style>
<h2>TableDetail</h2>
<div class="row">

    <div class="col-md-2">
        <table>
            <tr>
                @{
                    List<string[]> list = (List<string[]>)ViewData["TableDetail"];
                    for (int j = 0; j < list[0].Length - 1; j++)
                    {
                        <th>@list[0][j].ToString()</th>
                    }
                }
            </tr>
            @{
                for (int i = 1; i < list.Count; i++)
                {
                    <tr>
                        @for (int j = 0; j < list[i].Length - 1; j++)
                        {
                            <td>@list[i][j].ToString()</td>
                        }
                    </tr>
                }
            }
        </table>
    </div>
</div>

Dev_Center/Views/Table/TableList.cshtml
<style>
    table, th, td {
        border: 1px solid black;
        border-collapse: collapse;
        padding: 15px;
    }

    .side {
        flex: 30%;
        background-color: #f1f1f1;
        padding: 20px;
    }

    /* Main column */
    .main {
        flex: 70%;
        background-color: white;
        padding: 20px;
    }
</style>
<div>
    <h2>TableList</h2>
    @using (Html.BeginForm("Filter","Table"))
    {
        <input name="Filterv" id="Filterv" type="text" />

        <input type="submit" value="Filter" />
    }
</div>
<div class="row">
    <div class="col-md-2">
        <table>
            <tr>
                @{
                    List<string[]> list = (List<string[]>)ViewData["TableList"];
                    for (int j = 0; j < list[0].Length - 1; j++)
                    {
                        <th>@list[0][j].ToString()</th>
                    }
                }
            </tr>
            @{
                for (int i = 1; i < list.Count; i++)
                {
            <tr>
                @for (int j = 0; j < list[i].Length - 1; j++)
                {
                    if (j == 0)
                    {
                        <td>@Html.ActionLink(list[i][j].ToString(), $"TableDetail", "Table",new{table=list[i][j].ToString()},null)</td>
                    }
                    else
                    {
                        <td>@list[i][j].ToString()</td>
                    }
                }
            </tr>
                }
            }
        </table>
    </div>
</div>

Dev_Center/Views/Table/TableShema.cshtml
<style>
    table, th, td {
        border: 1px solid black;
        border-collapse: collapse;
        padding: 15px;
    }

    .side {
        flex: 30%;
        background-color: #f1f1f1;
        padding: 20px;
    }

    /* Main column */
    .main {
        flex: 70%;
        background-color: white;
        padding: 20px;
    }
</style>
<h2>TableDetail</h2>
<div class="row">

    <div class="col-md-2">
        <table>
            <tr>
                @{
                    List<string[]> list = (List<string[]>)ViewData["TableShema"];
                    for (int j = 0; j < list[0].Length - 1; j++)
                    {
                        <th>@list[0][j].ToString()</th>
                    }
                }
            </tr>
            @{
                for (int i = 1; i < list.Count; i++)
                {
                    <tr>
                        @for (int j = 0; j < list[i].Length - 1; j++)
                        {
                            <td>@list[i][j].ToString()</td>
                        }
                    </tr>
                }
            }
        </table>
    </div>
</div>